title: QSystems Biology
email: qiaosu.qs@gmail.com
description: >-
  A personal academic portfolio of Qiao Su â€” Systems Biology, Omics, and Precision Health.
github_username: iqiaosu
minimal_mistakes_skin: default
search: false

# --- Build settings ---
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jemoji
  - jekyll-feed
  - jekyll-sitemap

# --- Site output ---
permalink: /:categories/:title/
# ç¦ç”¨åˆ†é¡µ
# paginate: 5
# paginate_path: /page:num/


include:
  - _pages

# --- Author profile (ä»…ç”¨äºmetaï¼Œä¸ä¼šæ˜¾ç¤ºåœ¨ä¾§æ ) ---
author:
  name   : "Qiao Su"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "BSBA *CPU*, MSc *Chongqing*, PhD *Melbourne* <br><br>ğŸš— Road trip <br>ğŸ“˜ Reading <br>ğŸ“¸ Photography <br>ğŸ€ Basketball <br>ğŸ’ƒ Street dance bug <br>â™  Board game <br>ğŸ„ Surfing rookie"
  email  : "qiaosu.qs@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/iqiaosu"

# --- Defaults for posts & pages ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: "sidebar"   # âœ… è®©æ–‡ç« ä¹Ÿç”¨å·¦ä¾§çš„åŒä¸€å¥—å¯¼èˆª

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

header:
  nav: []   # æ¸…ç©ºé¡¶éƒ¨å¯¼èˆª

# è‡ªå®šä¹‰æ ·å¼åŠ è½½
head_scripts:
  - /_includes/custom-style.html


